"""Pydantic schemas for articles, filters, and paginated responses."""

from typing import List, Optional
from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field

from fan_zone.models.enums import IngestionStatus
from fan_zone.schemas.source import SourceSummarySchema
from fan_zone.schemas.media import MediaCreate, MediaSchema
from fan_zone.schemas.tag import TagSchema


class ArticleBase(BaseModel):
    original_title: str = Field(..., description="Original extracted headline from publisher")
    original_subtitle: Optional[str] = Field(None, description="Original extracted subtitle/subheadline")
    author: Optional[str] = Field(None, description="Article author name if detected")
    published_at: Optional[datetime] = Field(None, description="Publication timestamp")
    raw_paragraphs: List[str] = Field(default_factory=list, description="Extracted body paragraphs")
    cleaned_body: Optional[str] = Field(None, description="Consolidated clean text body")
    raw_html: Optional[str] = Field(None, description="Raw HTML source of article body")
    ai_headline: Optional[str] = Field(None, description="Non-clickbait objective headline generated by AI")
    ai_subheadline: Optional[str] = Field(None, description="Concise summary subheadline generated by AI")
    summary: Optional[str] = Field(None, description="Longer summary if generated")
    sport: Optional[str] = Field(None, description="Primary sport category (e.g. כדורגל)")
    competition: Optional[str] = Field(None, description="League or tournament (e.g. ליגת העל)")
    teams_json: List[str] = Field(default_factory=list, description="List of team names in Hebrew")
    players_json: List[str] = Field(default_factory=list, description="List of player/coach names")
    tags_json: List[str] = Field(default_factory=list, description="General entity/topic tags")
    ingestion_status: IngestionStatus = Field(default=IngestionStatus.PENDING, description="Pipeline processing state")
    error_message: Optional[str] = Field(None, description="Last error message if failed")


class ArticleCreate(ArticleBase):
    source_id: int = Field(..., description="Foreign key reference to source")
    canonical_url: str = Field(..., description="Normalized canonical article URL")
    content_hash: Optional[str] = Field(None, description="SHA-256 hash of title and paragraphs")
    original_subheadline: Optional[str] = None
    paragraphs: Optional[List[str]] = None
    media: Optional[List[MediaCreate]] = None


class ArticleUpdate(BaseModel):
    ai_headline: Optional[str] = None
    ai_subheadline: Optional[str] = None
    summary: Optional[str] = None
    sport: Optional[str] = None
    competition: Optional[str] = None
    teams_json: Optional[List[str]] = None
    players_json: Optional[List[str]] = None
    tags_json: Optional[List[str]] = None
    ingestion_status: Optional[IngestionStatus] = None
    error_message: Optional[str] = None
    cleaned_body: Optional[str] = None


class ArticleSummarySchema(BaseModel):
    id: int
    source_id: int
    canonical_url: str
    original_title: str
    original_subtitle: Optional[str] = None
    original_subheadline: Optional[str] = None
    ai_headline: Optional[str] = None
    ai_subheadline: Optional[str] = None
    author: Optional[str] = None
    published_at: Optional[datetime] = None
    sport: Optional[str] = None
    competition: Optional[str] = None
    teams: List[str] = Field(default_factory=list)
    players: List[str] = Field(default_factory=list)
    tags: List[str] = Field(default_factory=list)
    lead_image: Optional[MediaSchema] = None
    source: Optional[SourceSummarySchema] = None
    ingestion_status: IngestionStatus
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)


class ArticleDetailSchema(ArticleSummarySchema):
    raw_paragraphs: List[str] = Field(default_factory=list)
    paragraphs: List[str] = Field(default_factory=list)
    cleaned_body: Optional[str] = None
    raw_html: Optional[str] = None
    summary: Optional[str] = None
    media: List[MediaSchema] = Field(default_factory=list)
    tags_detail: List[TagSchema] = Field(default_factory=list, alias="tags_detail")

    model_config = ConfigDict(from_attributes=True, populate_by_name=True)


class ArticleFilter(BaseModel):
    source_id: Optional[int] = None
    source_name: Optional[str] = None
    sport: Optional[str] = None
    team: Optional[str] = None
    competition: Optional[str] = None
    tag: Optional[str] = None
    status: Optional[IngestionStatus] = None
    date_from: Optional[datetime] = None
    date_to: Optional[datetime] = None
    search_query: Optional[str] = None
    skip: int = 0
    limit: int = 20
    sort_by: str = "published_at"
    sort_desc: bool = True


class PaginatedArticleResponse(BaseModel):
    items: List[ArticleSummarySchema]
    total: int
    page: int
    page_size: int
    total_pages: int
    has_next: bool
    has_prev: bool
